pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        PACKER_DIR = 'packer'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Packer Init & Validate') {
            steps {
                withCredentials([aws(credentialsId: 'aws-packer-credentials', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    dir("${env.PACKER_DIR}") {
                        sh 'packer init aws-windows-2022.pkr.hcl'
                        sh 'packer validate aws-windows-2022.pkr.hcl'
                    }
                }
            }
        }

        stage('Build Windows AMI') {
            steps {
                withCredentials([aws(credentialsId: 'aws-packer-credentials', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    dir("${env.PACKER_DIR}") {
                        sh 'packer build aws-windows-2022.pkr.hcl'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}