pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        PACKER_DIR = 'ami-builder-windows/packer'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Packer Init & Validate') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws-packer-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    dir("${env.PACKER_DIR}") {
                        sh 'packer init .'
                        sh 'packer validate .'
                    }
                }
            }
        }

        stage('Build Windows AMI') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws-packer-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    dir("${env.PACKER_DIR}") {
                        sh 'packer build .'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}